### ISSUE TITLE
CORS-header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by ryandegruyter** [oraj-360/timeline-service#1]

**Comment by TYsewyn** [comment]
@ryandegruyter could you elaborate more on this issue? All communication should go through the API gateway, so it shouldn't be possible to access this service directly.

**Comment by KevinDaHub** [comment]
The gateway handles the CORS issue. Please communicatie with the gateway on the front end

**Comment by ryandegruyter** [comment]
Ok, gateway is having issues(returning empty response bodies) so I was trying to access the timeline service directly. Ill wait untill gateway is fixed and communicate with that service.
